### ISSUE TITLE
[Playground] oasis 0.6

### ISSUE THREAD

**Issue by zhuxudong** [oasis-engine/oasis-engine.github.io#294]
### Feature
- [x] video background https://github.com/oasis-engine/oasis-engine.github.io/pull/293 @zhuxudong 
- [x] HDR/LDR comparision @zhuxudong 
- [x] Bake/ UnBake comparision @zhuxudong 
- [x] Input manager @cptbtptpbcptdtptp https://github.com/oasis-engine/oasis-engine.github.io/pull/330
- [x] Physical trigger @yangfengzzz #304 
- [x] AnimatorState Script @luzhuang 

### Refactor
- [x] physics raycast @yangfengzzz  #303 
- [x] physics collision @yangfengzzz #303 
- [x] more primitive mesh @JujieX  
- [x] PBR workflow @zhuxudong
