### ISSUE TITLE
Iteration Plan: Milestone 0.8 - Document

### ISSUE THREAD

**Issue by cptbtptpbcptdtptp** [oasis-engine/oasis-engine.github.io#399]
### 更新（在现有文档上对内容的迭代）

- 快速入门
  - [0. 安装 Oasis Engine](https://oasisengine.cn/0.7/docs/install-cn) @GuoLei1990 
     - [x] 更新 Toolkit 相关内容
  - [1. 初始化画布](https://oasisengine.cn/0.7/docs/canvas-cn) @eyworldwide   https://github.com/oasis-engine/oasis-engine.github.io/pull/422
     - [x] 检查画布 clientWidth 与 clientHeight (为空时投影矩阵有误)
     - [x] 更新画布需要做的处理（resizeByClientSize）
  - [3. 加载一个 3D 模型](https://oasisengine.cn/0.7/docs/model-cn) @zhuxudong 
     - [x] 补充一下当前支持的格式（glTF文件，glb文件）
  - [5. 第一个游戏](https://oasisengine.cn/0.7/docs/first-game-cn) @cptbtptpbcptdtptp 
    - [x] 优化屏幕适配与碰撞部分逻辑
- 核心
  - [引擎](https://oasisengine.cn/0.7/docs/engine-cn) @GuoLei1990 
     - [x] 把设置帧率单独拉出来作为一个二级标题
     - [x] 将几个状态阶段细致说一下（new，run，pause，resume，destroy）
  - [场景](https://oasisengine.cn/0.7/docs/scene-cn)  @gz65555 #424 
     - [ ] 激活，合并与加载场景为一个二级标签
     - [ ] 场景的 background 设置为一个二级标签，内含纯色，天空盒等
     - [ ] 增加一张图说明 Engine 与 Scene， Scene 与 Root 的关系
     - [ ] 补充下取 Scene 的正确姿势 (engine.SceneManager ? this.scene?)
  - [实体与组件](https://oasisengine.cn/0.7/docs/entity-cn) @JujieX 
     - [x] 优化顺序，可以考虑先写实体的增删改查，在写组件的增删改查，然后实体与组件的关系（如何从组件内获取实体，从实体内获取组件）
     - [x] 写清楚实体与组件的 active，enable 和 destroy，包括主动与被动的情况下（主动即开发者调用 enable， 被动可能是开发者remove了这个 Entity）
     - [ ] 可以考虑增加如何写自定义组件
  - [脚本](https://oasisengine.cn/0.7/docs/script-cn) @luzhuang 
     - [ ] 更新脚本生命周期大图
  - [变换](https://oasisengine.cn/0.7/docs/transform-cn) @johanzhu 
     - [x] 增加对世界坐标的一些简单说明（右手坐标系，相机朝向等）
  - [克隆](https://oasisengine.cn/0.7/docs/entity-clone-cn) @GuoLei1990 
     - [x] 是否需要补充 _cloneTo 方法的说明？
- 图形
  - [相机组件](https://oasisengine.cn/0.7/docs/camera-cn) @cptbtptpbcptdtptp 
     - [x] 开篇先介绍透视投影和正交投影的使用和属性含义
     - [x] 相机的朝向和 lookat 函数
     - [x] 相机的渲染剔除（cullMask 和 Layer，需要描述 Layer 在层级中的影响关系和先后顺序）
     - [x] 单相机多次渲染 和 多相机渲染（单相机多次渲染主要讲onBeginRender 与 renderTarget，多相机主要讲CameraClearFlags，以及两者的性能差异）
  - [相机控件](https://oasisengine.cn/0.7/docs/controls-cn) @cptbtptpbcptdtptp 
     - [x] 修复 playground bug
  - [自定义材质](https://oasisengine.cn/0.7/docs/custom-material-cn) @zhuxudong 
     - [x] 可以把较多部分的内容移至材质总览（如内置shader变量，宏开关，渲染状态，渲染队列）
     - [x] 可以将渲染状态和渲染队列说得更清楚一些
  - [纹理总览](https://oasisengine.cn/0.7/docs/texture-cn#1-mipmap) @zhuxudong 
     - [x] UV 坐标
     - [ ] 纹理重复模式可能带来的问题（白边）
     - [x] 一些设置对性能的影响（主要是内存）
     - [x] 简单描述下纹理格式（R8G8B8A8 等）
  - [离屏渲染纹理](https://oasisengine.cn/0.7/docs/m-r-t-cn) @zhuxudong 
     - [x] 增加离屏渲染深度纹理
  - [纹理压缩](https://oasisengine.cn/0.7/docs/texture-compression-cn) @zhuxudong 
     - [x] 直接搞表格和示例，让他们可以一眼明白支持的压缩纹理类型，并且可以直接拷贝代码（只需换下URL）
  - [精灵渲染器](https://oasisengine.cn/0.7/docs/sprite-renderer-cn) @singlecoder 
     - [x] 参考坐标系与SpriteRender 在三维空间的位姿（平行于父节点的 XoY 平面，让开发者基本有个概念）
     - [ ] 补充说明包围盒以及渲染顺序
  - [精灵资源](https://oasisengine.cn/0.7/docs/sprite-cn) @singlecoder 
     - [x] Region 与 Pivot 的参考坐标原点
     - [x] Texture2D 与 Sprite 的关系，Sprite 的销毁
  - [精灵图集](https://oasisengine.cn/0.7/docs/sprite-atlas-cn) @cptbtptpbcptdtptp 
     - [x] 加载远端与本地图集资源
  - [文字渲染器](https://oasisengine.cn/0.7/docs/text-renderer-cn) @singlecoder 
     - [x] 多写些原子化的 playground 让开发者拷贝。
     - [x] 列举文字目前支持的能力与不支持的能力表格
- 动画
  - [动画组件](https://oasisengine.cn/0.7/docs/animator-cn#animator) @luzhuang  https://github.com/oasis-engine/oasis-engine.github.io/pull/425
     - [x] 重点突出一些案例如：
        - 播放速度控制（倒放，停止，继续等等）
        - Once 和 Loop
        - 从指定开始帧播到指定结束帧
        - 过渡混合
        - 指定跳转的某一帧
        - 事件派发（现在还是有些冗余）
     - [x] 对概念的介绍可以更直白一些，同时没有表现出动画层级结构中一对多的关系。 
     
  - [Spine](https://oasisengine.cn/0.7/docs/spine-cn) @johanzhu 
     - [ ] 特点与适用场景（让开发者知道什么情况下选 Spine）
     - [ ] 重点突出一些案例如：
        - 播放速度控制（倒放，停止，继续等等）
        - Once 和 Loop
        - 从指定开始帧播到指定结束帧
        - 过渡混合
        - 指定跳转的某一帧
        - 事件派发
  - [Lottie](https://oasisengine.cn/0.7/docs/lottie-cn) @eyworldwide **TODO：lottie 引擎还未适配，文档也延迟修改。**
      - [ ] 重点突出一些案例如：
        - 播放速度控制（倒放，停止，继续等等）
        - Once 和 Loop
        - 从指定开始帧播到指定结束帧
        - 过渡混合
        - 指定跳转的某一帧
        - 事件派发
  - [粒子动画](https://oasisengine.cn/0.7/docs/particle-renderer-cn) @eyworldwide **TODO：粒子待重构，文档先不动**
      - [ ] 2D 粒子与 3D 粒子在三维空间的大致位置（开发者大致有个感觉）
- 物理
  - [物理总览](https://oasisengine.cn/0.7/docs/physics-overall-cn) @yangfengzzz 
      - [x] 让开发者知道什么时候选 lite 什么时候选 physX（额外包大小，不同能力，性能，表现效果，wasm的平台适配等）
  - [物理管理器](https://oasisengine.cn/0.7/docs/physics-manager-cn) @yangfengzzz 
      - [x] 浏览器失焦后的追帧（maxSumTimeStep）
  - [碰撞器组件](https://oasisengine.cn/0.7/docs/physics-collider-cn) @yangfengzzz 
      - [x] 增加给 MeshRenderer 添加包围盒的示例（通过包围盒）
- 交互
  - [鼠标与触控](https://oasisengine.cn/0.7/docs/input-cn) @cptbtptpbcptdtptp 
      - [x] 兼容性与 PolyFill
- 资源
  - [资源管理与加载](https://oasisengine.cn/0.7/docs/resource-manager-cn) @gz65555 #428 
      - [ ] 加载了 A 其他地方如何获取这个资源
  - [glTF](https://oasisengine.cn/0.7/docs/gltf-cn) @zhuxudong 
      - [x] 补充一下当前支持的格式（glTF文件，glb文件）
      - [ ] 可以补充下 glTF 资源的压缩策略以及这些策略的平台兼容
      - [ ] 如何处理相对路径的 glTF

**Comment by cptbtptpbcptdtptp** [comment]
新增三篇：

- 相机取景与屏幕适配
- Oasis 内的坐标（三维空间坐标，viewpoint坐标，二维精灵坐标，UV坐标等等）
- 阴影（当前阴影的简单使用）

**Comment by cptbtptpbcptdtptp** [comment]
在写文档的时候，大家可以参考一下：

**Comment by yangfengzzz** [comment]
Engine-toolkit 的文档要怎么整合进去？

**Comment by cptbtptpbcptdtptp** [comment]
toolkit 需要新增一个目录
